# k8s/base/redis/headless-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: redis-headless-service # Descriptive name for the headless service
spec:
  # This makes the service "Headless." 
  # DNS queries will return the IP addresses of the individual Pods.
  clusterIP: None 
  
  # The selector must match the labels on the redis StatefulSet's Pods
  selector:
    app: redis-stateful
    
  # The ports section defines how the service exposes the pods
  ports:
    # redis's default port
    - port: 27017
      targetPort: 27017
      name: redis